### ISSUE TITLE
Provide bundling instructions

### ISSUE THREAD

**Issue by kyeotic** [hayd/deno-lambda#111]
First of all **thank you so much for this toolkit**, having a deno lambda layer is awesome! 🎉 

This is a feature request for users that want to build their own layer. Our company has strict policies against using external layers, so we need to bake and create out own. The [instructions](https://github.com/hayd/deno-lambda/blob/56d8b4e4030c0096f7b5c589ba1194201e2f97dc/QUICK-START.md) in the README assume we are working from the released ZIP. It would be awesome if this was extended to show how to create the layer zip from source.

This would also enable users finer control over the produced layer, in case they wanted to make small source changes before producing the layer zip.

**Comment by lucacasonato** [comment]
Here are the steps:

1. Build a amazonlinux1 compatible deno binary. Steps required can be found in this docker file: https://github.com/hayd/deno-docker/blob/master/amazonlinux1.dockerfile
2. Build the layer zip by copying the built deno executable for amzlinux1 and the bootstrap shell file into a zip file (with the right folder structure). You can see this being done automatically in this docker file: https://github.com/hayd/deno-lambda/blob/master/tests/Dockerfile

**Comment by kyeotic** [comment]
Just to be clear, this would be the minimal path to produce a working zip layer?

1. Build docker
```dockerfile
# Note: This must be built in the .. context
FROM hayd/amazonlinux1-deno:1.4.6

RUN yum install -y unzip zip

# /var/task has function code
# /opt has the layer code
RUN mkdir -p /src/runtime/bin /src/tests/bin /var/task /opt \
  && cp /bin/deno /src/runtime/bin/deno \
  && cp /bin/deno /src/tests/bin/deno

ADD hello.ts /src/runtime/hello.ts
ADD tests/pad.ts /src/runtime/pad.ts
ADD runtime /src/runtime

WORKDIR /src/runtime
RUN sh artifacts \
  && cp bootstrap /src/tests/bootstrap

```

2. Extract zip

```bash
docker cp extract:/src/runtime/deno-lambda-layer.zip deno-lambda-layer.zip
```

It took a bit of tinkering to get the Dockerfile to contain the right stuff needed by the `artifacts` script. I think it might be worth breaking this stuff out so that its not so intertwined with the tests code

**Comment by kyeotic** [comment]
@lucacasonato I was able to get a zip out of those, but it was not straightforward. The Dockerfile in `tests` has a lot of code that is unnecessary, and figuring out what was needed took some trial and error. It would be nice to see them broken out a little more.

I would be happy to create a PR for this if its something you are open to.

On a slightly unrelated note, have you considered moving to amazon linux 2? Lambda layers has support for it, and it's supposedly a little faster.

**Comment by hayd** [comment]
@kyeotic Moving to Amazon Linux 2 would definitely make things easier... I had totally missed this blogpost: https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/

Hopefully it's easy to migrate - this would make updating deno-lambda much easier/faster.

---

RE The [release example/layer](https://github.com/hayd/deno-lambda/releases/tag/1.5.2) also has the .zip files with the correct structure (you can upload these and they'd work). That said, perhaps adding something about this on the README would make a lot of sense...

**Comment by kyeotic** [comment]
Oh dip, I didn't know EOL was so close!

**Comment by hayd** [comment]
I think there is actually a bug, where by the bundling didn't work correctly (it was supposed to be that including bin/deno binary would suffice but this actually wasn't the case).

**Comment by hayd** [comment]
@kyeotic Re-reading the "Legacy runtime end-of-life schedules" section (and its table), I think provided (al1) will be **deprecated** at the end of December 2020.

> According to our runtime support policy, deprecation occurs in two phases:
>
>     Phase 1: you can no longer create functions that use the deprecated runtime. For at least 30 days, you can continue to update existing functions that use the deprecated runtime.
>     Phase 2: both function creation and updates are disabled permanently. However, the function continues to be available to process invocation events.

so I think we need to just do the move...

**Comment by kyeotic** [comment]
Well that's an interesting way to treat a runtime during it's maintenance period.
