### ISSUE TITLE
`event.path` is returning `undefined`

### ISSUE THREAD

**Issue by awcrotwell** [hayd/deno-lambda#125]
Using the example from the read me. The request spits out okay. I am really just trying to use [severless_oak](https://deno.land/x/serverless_oak@0.1.1/mod.ts). I am going through trying to debug it. On [Line 22](https://deno.land/x/serverless_oak@0.1.1/mod.ts#L22), it uses `event.path`. 

So I decided to take the example from your readme and try to access the path like so:

```js
import {
  APIGatewayProxyEvent,
  APIGatewayProxyResult,
  Context,
} from "https://deno.land/x/lambda/mod.ts";

export async function handler(
  event: APIGatewayProxyEvent,
  context: Context,
): Promise<APIGatewayProxyResult> {
  console.log(event);
  console.log(event.path);
  console.log(context);
  return await {
    body: `Welcome to deno ${Deno.version.deno} 🦕`,
    headers: { "content-type": "text/html;charset=utf8" },
    statusCode: 200,
  };
}
```

As I said before, the request comes out fine, event looks like it has a path sitting in the `http` object but typescript prevents me from accessing it and `event.path` is logging `undefined` in this example. Any ideas on how to remedy this? This is running aws lambda with amazon linux 2. I followed the SAR guide to deploy. I added an api gateway so i can hit it in my browser instead of using the test function.

Update:
I think I got it. `APIGatewayProxyEventV2` is the event type I should be using. I can use `rawPath` for fetching the path. Then i just configure to API Gateway with a `/` path so I can hit the server with "XXXX.execute-api.us-east-2.amazonaws.com" and `event.rawPath` will return `/`. 

Is this the proper way to do this or should I handle this another way? First time deploying a lambda function manually. Usually use serverless with nextjs.

**Comment by hayd** [comment]
It reads like we should be using APIGatewayProxyEventV2 everywhere (since APIGateway uses 2.0 by default)?
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

I think so... this also seems to be what @lucacasonato is using in deno_registry2.

**Comment by hayd** [comment]
examples are updated now
