### ISSUE TITLE
Release Amazon Linux1 / CentOS7 builds

### ISSUE THREAD

**Issue by recursionbane** [hayd/deno-lambda#131]
@hayd, referencing [this](https://github.com/denoland/deno/issues/1658#issuecomment-761698597) comment, could you please re-enable builds for CentOS7 (i.e., Amazon Linux 1) builds?

It doesn't look like Deno will supply official binaries for CentOS7.

Thanks in advance!

**Comment by hayd** [comment]
I spend some time trying to redo this, but haven't yet had success. If anyone has a working dockerfile for centos7 that would be very helpful!

**Comment by hayd** [comment]
I think this probably ought to be an issue on https://github.com/denoland/deno_docker
I think this is out of scope for deno-lambda now.
