### ISSUE TITLE
types.ts.d contains references to non-existing sources

### ISSUE THREAD

**Issue by happycodelucky** [hayd/deno-lambda#134]
I'm unable to import the lambda module when using `deno run` or `deno cache` due to export declarations to unavailable sources. See https://github.com/hayd/deno-lambda/blob/853879fa2f45a4b4b75240ba12b9870bf2a3f413/runtime/types.d.ts#L1434-L1444

This seems to have been introduce in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/aws-lambda/trigger/cognito-user-pool-trigger/index.d.ts#L109-L119

Looks like v1.9-1 is fine, and was problematic in v1.10.2

Here's the log
```
Download https://deno.land/x/lambda/mod.ts
Warning Implicitly using latest version (1.10.2) for https://deno.land/x/lambda/mod.ts
Download https://deno.land/x/lambda@1.10.2/mod.ts
Download https://deno.land/x/lambda@1.10.2/types.d.ts
Download https://deno.land/x/lambda@1.10.2/create-auth-challenge
Download https://deno.land/x/lambda@1.10.2/custom-message
Download https://deno.land/x/lambda@1.10.2/post-authentication
Download https://deno.land/x/lambda@1.10.2/verify-auth-challenge-response
Download https://deno.land/x/lambda@1.10.2/custom-email-sender
Download https://deno.land/x/lambda@1.10.2/pre-token-generation
Download https://deno.land/x/lambda@1.10.2/post-confirmation
Download https://deno.land/x/lambda@1.10.2/user-migration
Download https://deno.land/x/lambda@1.10.2/define-auth-challenge
Download https://deno.land/x/lambda@1.10.2/pre-authentication
Download https://deno.land/x/lambda@1.10.2/pre-signup
error: Import 'https://deno.land/x/lambda@1.10.2/create-auth-challenge' failed: 404 Not Found
    at https://deno.land/x/lambda@1.10.2/types.d.ts:1434:0
```

**Comment by hayd** [comment]
Oh no! I thought I had fixed this (and tested the types file in CI).

The initial fix is to simply remove those lines, but the better fix is to iteratively import those types (the types updater is a little hacky...).

Please for now import `lambda@v1.9-1`

**Comment by hayd** [comment]
Should be fixed now, I think I've updated the update script (and CI) so it won't happen again.
