### ISSUE TITLE
Published deno SAR is version 1.7.2, examples 1.10.2

### ISSUE THREAD

**Issue by happycodelucky** [hayd/deno-lambda#135]
The published application at [arn:aws:serverlessrepo:us-east-1:390065572566:applications~deno](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:390065572566:applications~deno) was uses a `SemanticVersion` `1.7.2`. 

This is a little problematic with all the [serverless framework](https://github.com/hayd/deno-lambda/blob/master/example-serverless/serverless.yml#L67), [SAM](https://github.com/hayd/deno-lambda/blob/master/example-sam/template.yml#L14), and others examples resources in uses `1.10.2`.

I imagine it would be ideal if the application was updated rather than the examples corrected? Good time to bump to 1.10.3 ;)

**Comment by hayd** [comment]
Doh! I suspect this is a bug in the publish CI step (which is failing) https://github.com/hayd/deno-lambda/actions/workflows/publish.yml

But will update to 1.10.3 and see if I can fix it up/ensure it's green.

Is there a page that shows which version is the most recent published?

**Comment by happycodelucky** [comment]
@hayd there not a page where it shows the SemanticVersion (that seems like a bit of a miss for them IMO). 

You can use the CLI: 

> `$ aws serverlessrepo get-application --application-id=arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno`

Or "Deploy" the application and it tells you the version once preparing to create a function, which is how I found it

**Comment by hayd** [comment]
@happycodelucky I think I have no published this, the issue seemed to be since github actions changed ubuntu-latest to 20.04 🤷 . I think I've pushed 1.10.3 to SAR now...

**Comment by happycodelucky** [comment]
You did, it's working with a serverless deployment using 1.10.3. 

Thanks for the update!! I'll close this out
