### ISSUE TITLE
no such file or directory error (../runtime/mod.ts) 

### ISSUE THREAD

**Issue by outofoffice3** [hayd/deno-lambda#189]
Hayd, 

I followed your directions on using **SAR** as well as the **ZIP based deploy** for the deno-lambda hello.ts.  

Each time I have this error where:  

import {
  APIGatewayProxyEventV2,
  APIGatewayProxyResultV2,
  Context,
} from "../runtime/mod.ts";

Is not resolving & is not found.  Am I doing something wrong?  Is the SAR deploy method not current?  I was able to work around it when I loaded them into a new directory I created (copy / paste workaround), but I'm curious as to why I wasn't able to do it as you prescribed.  Just want to make sure I am understanding your flow. 

Thank you!
<img width="1616" alt="Screen Shot 2022-07-06 at 12 04 42 AM" src="https://user-images.githubusercontent.com/99206634/177465861-d098cb22-5edb-463f-8e6e-c0743decff04.png">
<img width="1400" alt="Screen Shot 2022-07-06 at 12 06 49 AM" src="https://user-images.githubusercontent.com/99206634/177466099-7d334edc-9237-4973-a520-b4dc52bacdad.png">

**Comment by hayd** [comment]
You should probably use the full url: `https://deno.land/x/lambda/mod.ts` rather than the relative file ("../runtime/mod.ts").

I'll take a look to see if there is a better relative file to use (the problem with using a relative file is it may break local dev)...
