### ISSUE TITLE
1.x rc (and 1.x)

### ISSUE THREAD

**Issue by brianleroux** [hayd/deno-lambda#70]
hey! wondering if you're planning on releasing updated bits to SAR? I'd rather re-use your work and get rid of mine!

**Comment by hayd** [comment]
@brianleroux sorry for the slow response (GH didn't show this in my notifications, please use `@` next time :) ) - pushing 1.0.0-rc2 shortly!

**Comment by hayd** [comment]
Looks like it's deployed to SAR 🤞 https://github.com/hayd/deno-lambda/runs/660285585?check_suite_focus=true

Let me know if you have any issues/further feedback. 😎

**Comment by brianleroux** [comment]
np this is great thx!!!
