### ISSUE TITLE
Fix example-serverless on 1.0.0

### ISSUE THREAD

**Issue by hayd** [hayd/deno-lambda#72]
This doesn't work in 1.0.0-rc2,atm it's tested on 0.41.0 only, requires dynamodb to be updated.

https://github.com/chiefbiiko/dynamodb/issues/20

**Comment by artoliukkonen** [comment]
I also noticed that at least on MacOS Deno 1.0.0 doesn't work properly with `DENO_DIR` parameter that this example is using. I had to compile Deno from source, with the latest `master` plus updates coming to `dynamodb` & `get-aws-config` packages I got this working.

**Comment by hayd** [comment]
Is it that the full path is required in specifying DENO_DIR (that bug is present in 1.0.0 but fixed in deno master)?

Looking forward to a new dynamodb release with your fixes!🤞

**Comment by artoliukkonen** [comment]
Yea that DENO_DIR is because of relative path, is fixed here https://github.com/denoland/deno/pull/5375 . Didn't actually notice that absolute paths were already working :)

**Comment by hayd** [comment]
Thanks @artoliukkonen !
