### ISSUE TITLE
Serverless to run bundled js files

### ISSUE THREAD

**Issue by silver-xu** [hayd/deno-lambda#73]
When using serverless to deploy bundled file `dist.js`, it was reporting that 

```
START RequestId: 39dff4dd-6def-48d7-9830-52d5d8406efc Version: $LATEST
warn: unable to import '.deno_dir/' as DENO_DIR
error: Cannot resolve module "file:///var/task/dist.ts" from "file:///tmp/runtime.js"
[0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
Check the permission of the directory.
error: bad deno executable
END RequestId: 39dff4dd-6def-48d7-9830-52d5d8406efc
REPORT RequestId: 39dff4dd-6def-48d7-9830-52d5d8406efc	Duration: 164.47 ms	Billed Duration: 200 ms	Memory Size: 1024 MB	Max Memory Used: 11 MB	
Unknown application error occurred
Unhandled
```

It looks like the module is assuming .ts files by default

**Comment by hayd** [comment]
You need to set HANDLER_EXT to js, see https://github.com/hayd/deno-lambda#configuration

That said, this error is very confusing, why would it reference "/home/sbx_user1051/.cache/deno/gen" ??

**Comment by silver-xu** [comment]
Thanks for the reply. I believe it can be closed.

**Comment by hayd** [comment]
Ok. Could you explain what you did to get that error, I would like to make it more informative... I _thought_ that I had it so it would say "missing expected handler file":

https://github.com/hayd/deno-lambda/blob/888844bf2baae7b74c7cf17eed47ff9d57e1ea83/runtime/bootstrap#L78-L79

It confuses me/seems a bug that it is logging `error: bad deno executable`.
