### ISSUE TITLE
FEATURE REQUEST: Using Deno Permissions

### ISSUE THREAD

**Issue by silver-xu** [hayd/deno-lambda#74]
How will deno permission be set in serverless? Will it always default to allow all?

**Comment by hayd** [comment]
At the moment it's -A, I'd be open to being more precise... though I'm not sure how valuable it would be since many permissions are required for the runtime to work.

https://github.com/hayd/deno-lambda/blob/888844bf2baae7b74c7cf17eed47ff9d57e1ea83/runtime/bootstrap#L17-L20

**Comment by hayd** [comment]
I'm going to close this, but I'm still open to ideas to what this would look like... I think this would be much easier if/when realms are a thing (so the handler function could be called with reduced permissions).
