### ISSUE TITLE
Understanding Remapping

### ISSUE THREAD

**Issue by garysb** [hayd/deno-lambda#78]
I'm just trying to understand why we need to remap the DENO_DIR? I have read through [DENO_DIR Remapping](https://github.com/hayd/deno-lambda/blob/master/README.md#deno_dir-remapping) but don't understand why `$ deno bundle` would not work? Does `$ deno bundle` not include external modules?

Thanks in advance for clarifying.

**Comment by hayd** [comment]
deno bundle does work, with deno bundle you will not need DENO_DIR remapping since there should be neither remote fetching or compilation. DENO_DIR is required only if you are not using deno bundle command.
