### ISSUE TITLE
can not find deno with https://github.com/lambci/docker-lambda?

### ISSUE THREAD

**Issue by davidxiao** [hayd/deno-lambda#81]
hi,
  I tried to play this with `local lambda`, while getting the below error:

111 #### PATH=/var/task/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
222 #### pwd=/var/task
/var/task/bootstrap: line 238: deno: command not found

line 238 is below line, i tried to echo out the path and pwd
https://github.com/hayd/deno-lambda/blob/master/runtime/bootstrap#L236

reckon if it's related to lambda image ? because that `deno` can not run in Mac as well

BTW, what is https://github.com/hayd/deno-lambda/releases/download/1.0.2/amz-deno.gz and what it's for?

**Comment by hayd** [comment]
What did you do to try this?

I _reads_ like, but I haven't tested, that you could unzip the deno-lambda-layer.zip and use that with the provided runtime. It's critical deno-lambda's bootstrap and bin/deno are in there, the deno-lambda-layer.zip demonstrates the correct structure.

deno-lambda ships with its own deno binary, that is important (the mac one won't work), it's included in deno-lambda-layer.zip (in the correct location to be found by lambda in the PATH). (That same binary is also gzipped individually as amz-deno.gz.)

From docker-lambda readme:

```sh
# Test with a provided runtime (assumes you have a `bootstrap` executable in the current directory)
docker run --rm -v "$PWD":/var/task:ro,delegated lambci/lambda:provided handler '{"some": "event"}'
```

If you get this working, please comment the steps you went through., thanks!

**Comment by davidxiao** [comment]
yeah, i downloaded deno-lambda-layer.zip and unzipped it, then ran in the dir with unzipped files:
`docker run -d \
  -e DOCKER_LAMBDA_STAY_OPEN=1 \
  -p 9001:9001 \
  -v "$PWD":/var/task:ro,delegated \
  lambci/lambda:provided \
  handler`

`bootstrap` was running, so got the error message from `bootstrap`, the only thing I can think of now is reckon it's related to lambda OS?

**Comment by hayd** [comment]
I ran it and got `404 page not found`. 🤔 

I think it should be like:
```
docker run -e DOCKER_LAMBDA_STAY_OPEN=1 -p 9001:9001 -v "$PWD":/var/task:ro,delegated lambci/lambda:provided hello.handler
```

But I'm not sure it's even seeing bootstrap for me. 😕

**Comment by hayd** [comment]
Ah, got it:

The layer must be added as a layer (mounted at `/opt`)! Whilst the app itself is at `/var/task`. So, you can do the following:
```
❱ docker run -it --rm -v "$PWD":/var/task:ro,delegated -v "$PWD":/opt:ro,delegated lambci/lambda:provided hello.handler
START RequestId: c95f0609-b763-183e-56f2-22e72c2dae99 Version: $LATEST
END RequestId: c95f0609-b763-183e-56f2-22e72c2dae99
REPORT RequestId: c95f0609-b763-183e-56f2-22e72c2dae99	Init Duration: 244.58 ms	Duration: 9.18 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 30 MB

{"statusCode":200,"headers":{"content-type":"text/html;charset=utf8"},"body":"Welcome to deno 1.0.2 🦕"}
```

Using stay open:
```
❱ docker run -e DOCKER_LAMBDA_STAY_OPEN=1 -p 9001:9001 -it --rm -v "$PWD":/var/task:ro,delegated -v "$PWD":/opt:ro,delegated lambci/lambda:provided hello.handler
Lambda API listening on port 9001...
```
in another shell:
```
❱ aws lambda invoke --endpoint http://localhost:9001 --no-sign-request --function-name deno-func --payload '{}' output.json
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
❱ cat output.json
{"statusCode":200,"headers":{"content-type":"text/html;charset=utf8"},"body":"Welcome to deno 1.0.2 🦕"}
```

It probably makes sense to store the layer in a separate directory.

**Comment by davidxiao** [comment]
yeah, sorry for late response, can close the ticket
